version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: newsletter_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: newsletterdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  backend:
    build:
      context: ./backend
    image: newsletter_backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/newsletterdb
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/app/newsletter"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: newsletter_frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
