# Production Docker Compose file
# This file is used for production deployments with GHCR images
# The workflow will dynamically update the image tags with latest and SHA versions
# 
# SECURITY NOTE: This file contains placeholder values. In production, use environment
# variables or secrets for sensitive data like MINIO_ACCESS_KEY, MINIO_SECRET_KEY, etc.

services:
  frontend:
    image: ghcr.io/rust-cameroon/newsletter/frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/certs/rustcameroon.com-0001:/etc/letsencrypt/live/rustcameroon.com-0001:ro
    environment:
      - BACKEND_URL=http://backend:8000
      - VITE_API_URL=https://rustcameroon.com/api
      - NGINX_CONFIG=https
    user: "0:0"
    depends_on:
      - backend
      - minio
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  backend:
    image: ghcr.io/rust-cameroon/newsletter/backend:latest
    # SECURITY: Backend port is not exposed externally - only accessible via frontend
    # Remove the ports section to prevent direct access to backend
    volumes:
      - backend_data:/app/data
      - backend_images:/app/static/images
    environment:
      - RUST_LOG=info
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL:-postgres://user:password@localhost:5432/rustcameroon}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-http://localhost:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin123}
      - MINIO_BUCKET=${MINIO_BUCKET:-rust-cameroon-images}
    depends_on:
      minio:
        condition: service_healthy
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin123}
      - MINIO_BROWSER_REDIRECT_URL=https://rustcameroon.com/minio
      - MINIO_SERVER_URL=https://rustcameroon.com/minio
      - MINIO_DOMAIN=rustcameroon.com
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
  backend_data:
  backend_images:
