services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/rustcameroon.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/rustcameroon.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
    environment:
      - BACKEND_URL=http://backend:8000
      - VITE_API_URL=/api
      - NGINX_CONFIG=https
    user: "0:0"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/posts.json:/app/posts.json:ro
    environment:
      - RUST_LOG=info
      - PORT=8000
    restart: unless-stopped

