services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - BACKEND_URL=http://backend:8000
      - VITE_API_URL=/api
      - NGINX_CONFIG=http
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - ./backend/posts.json:/app/posts.json:ro
    environment:
      - RUST_LOG=info
      - PORT=8000
    restart: unless-stopped

